login_check:
    path:   /login_check

logout:
    path:   /logout

chiave_core_bundle:
    resource: "@ChiaveCoreBundle/Controller"
    prefix:   /
    type:     annotation

chiave_cms_bundle:
    resource: "@ChiaveCMSBundle/Controller"
    prefix:   /
    type:     annotation
