security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

# security:
#     role_hierarchy:
#         ROLE_ADMIN:       ROLE_USER
#         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

#         secured_area:
#             pattern:    ^/demo/secured/
#             form_login:
#                 check_path: _security_check
#                 login_path: _demo_login
#             logout:
#                 path:   _demo_logout
#                 target: _demo
#             #anonymous: ~
#             #http_basic:
#             #    realm: "Secured Demo Area"

#     access_control:
#         #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
