parameters:
#    chiave_cms.example.class: Chiave\CMSBundle\Example

services:
#    chiave_cms.example:
#        class: %chiave_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
