parameters:
#    chiave_cms.example.class: Chiave\CMSBundle\Example

services:
#    chiave_cms.example:
#        class: %chiave_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
   twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
