parameters:
#    musicisti_core.example.class: Musicisti\CoreBundle\Example

services:
#    musicisti_core.example:
#        class: %musicisti_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
